services:
  mysql:
    image: mysql:latest
    container_name: contenedor_compose
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: videojuegos  
    ports:
      - "3310:3306"
    volumes:
      - "C:/Users/Esteban/Desktop/Contenedores/compose:/var/lib/mysql"
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  mysql_data:
